In [5]:
import pandas as pd
from src.main import main

ModuleNotFoundError: No module named 'data_selector'

In [4]:
df = pd.read_csv('./data/csv/congreso_2019.csv', )
df

,Nombre de Comunidad,Código de Provincia,Nombre de Provincia,Código de Municipio,Nombre de Municipio,Población,Número de mesas,Total censo electoral,Total votantes,Votos válidos,...,UNIÓN REGIONALISTA,centrados,VOU,DP,PDSJE-UDEC,IZAR,RISA,C 21,+MAS+,UDT
0,Andalucía,4,Almería,1,Abla ...,1235,2,1014,768,763,...,0,0,0,0,0,0,0,0,0,0
1,Andalucía,4,Almería,2,Abrucena ...,1150,2,1039,798,792,...,0,0,0,0,0,0,0,0,0,0
2,Andalucía,4,Almería,3,Adra ...,24859,29,17540,12174,12051,...,0,0,0,0,0,0,0,0,0,0
3,Andalucía,4,Almería,4,Albánchez ...,753,1,400,320,315,...,0,0,0,0,0,0,0,0,0,0
4,Andalucía,4,Almería,5,Alboloduy ...,621,1,533,448,442,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8126,Comunitat Valenciana,46,Valencia / València,902,Gátova ...,392,1,356,300,296,...,0,0,0,0,0,0,0,0,0,0
8127,Comunitat Valenciana,46,Valencia / València,903,San Antonio de Benagéber ...,8846,8,6285,5035,4996,...,0,0,0,0,0,0,0,0,0,0
8128,Comunitat Valenciana,46,Valencia / València,904,Benicull de Xúquer ...,974,1,805,643,628,...,0,0,0,0,0,0,0,0,0,0
8129,Ciudad de Ceuta,51,Ceuta,1,Ceuta ...,85144,96,59934,38342,37884,...,0,0,0,0,0,0,0,0,0,0
8130,Ciudad de Melilla,52,Melilla,1,Melilla ...,86384,87,54129,34068,33749,...,0,0,0,0,0,0,0,0,0,0

In [8]:
ccaa_df = df.groupby(by=["Nombre de Comunidad"]).sum()

In [9]:
ccaa_df.index

Index(['Andalucía                     ', 'Aragón                        ',
       'Canarias                      ', 'Cantabria                     ',
       'Castilla - La Mancha          ', 'Castilla y León               ',
       'Cataluña                      ', 'Ciudad de Ceuta               ',
       'Ciudad de Melilla             ', 'Comunidad Foral de Navarra    ',
       'Comunidad de Madrid           ', 'Comunitat Valenciana          ',
       'Extremadura                   ', 'Galicia                       ',
       'Illes Balears                 ', 'La Rioja                      ',
       'País Vasco                    ', 'Principado de Asturias        ',
       'Región de Murcia              '],
      dtype='object', name='Nombre de Comunidad')

In [6]:
ccaa_df

,Código de Provincia,Código de Municipio,Población,Número de mesas,Total censo electoral,Total votantes,Votos válidos,Votos a candidaturas,Votos en blanco,Votos nulos,...,UNIÓN REGIONALISTA,centrados,VOU,DP,PDSJE-UDEC,IZAR,RISA,C 21,+MAS+,UDT
Nombre de Comunidad,,,,,,,,,,,,,,,,,,,,,
Andalucía,16361,77467,8384408,10126,6316975,4630265,4569140,4526162,42978,61125,...,0,0,0,0,0,253,187,0,0,0
Aragón,29478,110000,1308728,2175,982512,762588,754399,747456,6943,8189,...,0,0,0,0,0,0,0,0,46,28
Canarias,3242,2927,2127685,2825,1572767,1071879,1059050,1051455,7595,12829,...,0,0,0,0,0,0,0,0,0,0
Cantabria,3978,5253,580229,823,462906,361057,357287,354992,2295,3770,...,0,0,0,0,0,0,0,0,0,0
Castilla - La Mancha,19960,123563,2026807,3081,1539817,1201398,1184740,1176099,8641,16658,...,0,0,0,0,276,0,0,0,0,0
Castilla y León,68304,362705,2409164,4832,1961851,1533328,1513127,1499136,13991,20201,...,483,458,0,0,0,0,0,0,0,0
Cataluña,19932,141295,7600065,8373,5348330,4148683,4128116,4105921,22195,20567,...,0,0,0,0,0,0,0,0,0,0
Ciudad de Ceuta,51,1,85144,96,59934,38342,37884,37562,322,458,...,0,0,0,0,0,0,0,0,0,0
Ciudad de Melilla,52,1,86384,87,54129,34068,33749,33512,237,319,...,0,0,0,0,0,0,0,0,0,0
Comunidad Foral de Navarra,8432,42263,647554,976,483721,369163,365459,361699,3760,3704,...,0,0,0,0,0,0,0,0,0,0
Comunidad de Madrid,5012,18797,6578079,7590,4748700,3787554,3756107,3731602,24505,31447,...,0,0,0,0,0,0,0,0,0,0
Comunitat Valenciana,14279,62118,4963703,6044,3548044,2708312,2679049,2661393,17656,29263,...,0,0,0,0,0,0,0,0,0,0
Extremadura,3220,44440,1072863,1411,873056,666243,655380,650194,5186,10863,...,0,0,0,308,0,0,0,0,0,0
Galicia,8344,18012,2701743,3956,2240615,1657491,1633742,1616534,17208,23749,...,0,0,303,0,0,0,0,69,0,0
Illes Balears,469,3948,1128908,1215,774116,522993,517400,512754,4646,5593,...,0,0,0,0,0,0,0,0,0,0
La Rioja,4524,15681,315675,501,233625,182504,179995,178541,1454,2509,...,0,0,0,0,0,0,0,0,0,0
País Vasco,7187,31442,2199088,2667,1716993,1279990,1271005,1263031,7974,8985,...,0,0,0,0,0,0,0,0,0,0
Principado de Asturias,2574,3081,1028244,1573,856759,628445,621615,614846,6769,6830,...,0,0,0,0,0,0,0,0,0,0
Región de Murcia,1350,2749,1478509,1687,1024570,775480,767205,762443,4762,8275,...,0,0,0,0,0,0,0,0,0,0

In [29]:
total_votos = ccaa_df.loc[:,'Votos válidos'].sum()
votos_por_asiento = total_votos//350

In [27]:
only_results_df = ccaa_df.drop(labels=['Código de Provincia', 'Código de Municipio', 'Población',
       'Número de mesas', 'Total censo electoral', 'Total votantes',
       'Votos válidos', 'Votos a candidaturas', 'Votos en blanco',
       'Votos nulos'], axis=1)

In [37]:
results = only_results_df // votos_por_asiento

In [36]:
results.sum().sum()

291

In [38]:
import io

In [59]:
df = pd.read_csv(io.StringIO(
"""
Yellows ,Whites ,Reds ,Greens ,Blues ,Pinks ,Total
Votes ,47000 ,16000 ,15800 ,12000 ,6100 ,3100 ,100000
Seats ,,,,,,,10
Hare Quota ,,,,,,,10000
Votes/Quota ,4.70 ,1.60 ,1.58 ,1.20 ,0.61 ,0.31 ,
Automatic seats ,4 ,1 ,1 ,1 ,0 ,0 ,7
Remainder ,0.70 ,0.60 ,0.58 ,0.20 ,0.61 ,0.31 ,
Highest-remainder seats ,1 ,1 ,0 ,0 ,1 ,0 ,3
Total seats ,5 ,2 ,1 ,1 ,1 ,0 ,10 
"""))

In [60]:
df.to_dict(orient="dict")

{'Yellows ': {'Votes ': 47000.0,
  'Seats ': nan,
  'Hare Quota ': nan,
  'Votes/Quota ': 4.7,
  'Automatic seats ': 4.0,
  'Remainder ': 0.7,
  'Highest-remainder seats ': 1.0,
  'Total seats ': 5.0},
 'Whites ': {'Votes ': 16000.0,
  'Seats ': nan,
  'Hare Quota ': nan,
  'Votes/Quota ': 1.6,
  'Automatic seats ': 1.0,
  'Remainder ': 0.6,
  'Highest-remainder seats ': 1.0,
  'Total seats ': 2.0},
 'Reds ': {'Votes ': 15800.0,
  'Seats ': nan,
  'Hare Quota ': nan,
  'Votes/Quota ': 1.58,
  'Automatic seats ': 1.0,
  'Remainder ': 0.58,
  'Highest-remainder seats ': 0.0,
  'Total seats ': 1.0},
 'Greens ': {'Votes ': 12000.0,
  'Seats ': nan,
  'Hare Quota ': nan,
  'Votes/Quota ': 1.2,
  'Automatic seats ': 1.0,
  'Remainder ': 0.2,
  'Highest-remainder seats ': 0.0,
  'Total seats ': 1.0},
 'Blues ': {'Votes ': 6100.0,
  'Seats ': nan,
  'Hare Quota ': nan,
  'Votes/Quota ': 0.61,
  'Automatic seats ': 0.0,
  'Remainder ': 0.61,
  'Highest-remainder seats ': 1.0,
  'Total seats ': 1.0},
 'Pinks ': {'Votes ': 3100.0,
  'Seats ': nan,
  'Hare Quota ': nan,
  'Votes/Quota ': 0.31,
  'Automatic seats ': 0.0,
  'Remainder ': 0.31,
  'Highest-remainder seats ': 0.0,
  'Total seats ': 0.0},
 'Total': {'Votes ': 100000.0,
  'Seats ': 10.0,
  'Hare Quota ': 10000.0,
  'Votes/Quota ': nan,
  'Automatic seats ': 7.0,
  'Remainder ': nan,
  'Highest-remainder seats ': 3.0,
  'Total seats ': 10.0}}

In [64]:
expected_results = pd.DataFrame.from_dict(
        {
            "Yellows ": {
                "Votes ": 47000.0,
                "Seats ": None,
                "Hare Quota ": None,
                "Votes/Quota ": 4.7,
                "Automatic seats ": 4.0,
                "Remainder ": 0.7,
                "Highest-remainder seats ": 1.0,
                "Total seats ": 5.0,
            },
            "Whites ": {
                "Votes ": 16000.0,
                "Seats ": None,
                "Hare Quota ": None,
                "Votes/Quota ": 1.6,
                "Automatic seats ": 1.0,
                "Remainder ": 0.6,
                "Highest-remainder seats ": 1.0,
                "Total seats ": 2.0,
            },
            "Reds ": {
                "Votes ": 15800.0,
                "Seats ": None,
                "Hare Quota ": None,
                "Votes/Quota ": 1.58,
                "Automatic seats ": 1.0,
                "Remainder ": 0.58,
                "Highest-remainder seats ": 0.0,
                "Total seats ": 1.0,
            },
            "Greens ": {
                "Votes ": 12000.0,
                "Seats ": None,
                "Hare Quota ": None,
                "Votes/Quota ": 1.2,
                "Automatic seats ": 1.0,
                "Remainder ": 0.2,
                "Highest-remainder seats ": 0.0,
                "Total seats ": 1.0,
            },
            "Blues ": {
                "Votes ": 6100.0,
                "Seats ": None,
                "Hare Quota ": None,
                "Votes/Quota ": 0.61,
                "Automatic seats ": 0.0,
                "Remainder ": 0.61,
                "Highest-remainder seats ": 1.0,
                "Total seats ": 1.0,
            },
            "Pinks ": {
                "Votes ": 3100.0,
                "Seats ": None,
                "Hare Quota ": None,
                "Votes/Quota ": 0.31,
                "Automatic seats ": 0.0,
                "Remainder ": 0.31,
                "Highest-remainder seats ": 0.0,
                "Total seats ": 0.0,
            },
            "Total": {
                "Votes ": 100000.0,
                "Seats ": 10.0,
                "Hare Quota ": 10000.0,
                "Votes/Quota ": None,
                "Automatic seats ": 7.0,
                "Remainder ": None,
                "Highest-remainder seats ": 3.0,
                "Total seats ": 10.0,
            },
        }
)
expected_results["Total"] = expected_results.sum(axis=1)

In [65]:
expected_results

,Yellows,Whites,Reds,Greens,Blues,Pinks,Total
Votes,47000.0,16000.0,15800.00,12000.0,6100.00,3100.00,200000.0
Seats,NaN,NaN,NaN,NaN,NaN,NaN,10.0
Hare Quota,NaN,NaN,NaN,NaN,NaN,NaN,10000.0
Votes/Quota,4.7,1.6,1.58,1.2,0.61,0.31,10.0
Automatic seats,4.0,1.0,1.00,1.0,0.00,0.00,14.0
Remainder,0.7,0.6,0.58,0.2,0.61,0.31,3.0
Highest-remainder seats,1.0,1.0,0.00,0.0,1.00,0.00,6.0
Total seats,5.0,2.0,1.00,1.0,1.00,0.00,20.0

In [68]:
pd.DataFrame.from_dict(
{
            "Yellows ": {
                "Votes ": 47000.0,
            },
            "Whites ": {
                "Votes ": 16000.0,
            },
            "Reds ": {
                "Votes ": 15800.0,
            },
            "Greens ": {
                "Votes ": 12000.0,
            },
            "Blues ": {
                "Votes ": 6100.0,
            },
            "Pinks ": {
                "Votes ": 3100.0,
            },
            "Total": {
                "Votes ": 100000.0,
                "Seats ": 10.0,
                "Hare Quota ": 10000.0,
                "Votes/Quota ": None,
                "Automatic seats ": 7.0,
                "Remainder ": None,
                "Highest-remainder seats ": 3.0,
                "Total seats ": 10.0,
            },
        }
    )

,Yellows,Whites,Reds,Greens,Blues,Pinks,Total
Votes,47000.0,16000.0,15800.0,12000.0,6100.0,3100.0,100000.0
Seats,NaN,NaN,NaN,NaN,NaN,NaN,10.0
Hare Quota,NaN,NaN,NaN,NaN,NaN,NaN,10000.0
Votes/Quota,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Automatic seats,NaN,NaN,NaN,NaN,NaN,NaN,7.0
Remainder,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Highest-remainder seats,NaN,NaN,NaN,NaN,NaN,NaN,3.0
Total seats,NaN,NaN,NaN,NaN,NaN,NaN,10.0